version: '3'

tasks:
  default:
    cmds:
      - echo GQL-TODO
  client:
    dir: client
    cmds:
      - pnpm run dev
  server:
    dir: server
    cmds:
      - pnpm run start
  db-up:
    dir: docker
    cmds:
      - docker-compose up -d
  db-down:
    dir: docker
    cmds:
      - docker-compose down
  db-in:
    dir: docker
    cmds:
      - docker exec -it postgres /bin/sh