version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
volumes:
  db-store:
